# fly.toml app configuration file generated for sorcelapp on 2024-05-24T12:55:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sorcelapp'
primary_region = 'cdg'

[build]

[env]
  PORT = "3000"
  HOST = "https://sorcelapp.fly.dev"
  SHOPIFY_API_KEY = "82f3b9571b20a8b77db30e030ce7d536"
  SCOPES = "read_discounts,read_gates,write_discounts,write_gates,write_products"
  VITE_BACKEND_URL = "https://sorcelapp.fly.dev"
  VITE_ENV = "PROD"
  NODE_ENV="production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
