# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "82f3b9571b20a8b77db30e030ce7d536"
name = "sorcel"
handle = "sorcel"
application_url = "https://simulations-sat-aug-boc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tokengatingtestshop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_gates,write_discounts,write_gates,write_products"

[auth]
redirect_urls = [
  "https://simulations-sat-aug-boc.trycloudflare.com/auth/callback",
  "https://simulations-sat-aug-boc.trycloudflare.com/auth/shopify/callback",
  "https://simulations-sat-aug-boc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
